version: '3'

services:

  # Nginx web server acting as a reverse proxy for "web" and "api" services
  nginx:
    image: nginx:1.13.1-alpine
    read_only: true
    tmpfs:
      - /var/cache/nginx
      - /var/log/nginx
      - /var/run
    depends_on:
      - api
    ports:
      - "8880:80"
      - "8443:443"
    volumes:
      - ./config/docker/nginx-snippets:/etc/nginx/snippets:ro
      - ./config/docker/nginx.conf:/etc/nginx/conf.d/default.conf:ro

  # Data API and authentication/authorization
  api:
    image: node:8.1.2
    hostname: api
    depends_on:
      - db
      - redis
    # SESSION_SECRET, FACEBOOK_ID, and FACEBOOK_SECRET are defined in `.env`.
    # We define them here without a value to pass them down to the container.
    environment:
      - CORS_ORIGIN=http://localhost:3200
      - DATABASE_URL=postgres://postgres@db:5432/dev
      - DATABASE_DEBUG=false
      - REDIS_URL=redis://redis:6379/0
      - SESSION_SECRET
      - FACEBOOK_ID
      - FACEBOOK_SECRET
    expose:
      - "8880"
    ports:
      - "5000:5000" # WebSockets port
      - "9229:9229" # V8 inspector (when NODE_DEBUG=true)
    volumes:
      - yarn:/root/.cache/yarn
      - ./:/usr/src/app
    user: node
    working_dir: /usr/src/app
    command: node tools/run.js

  # SQL and document data store
  db:
    image: postgres:9.6.3-alpine
    read_only: true
    ports:
      - "5433:5432"
    tmpfs:
      - /tmp
      - /var/run/postgresql
    volumes:
      - db:/var/lib/postgresql/data
      - ./config/docker/postgres-initdb.sh:/docker-entrypoint-initdb.d/initdb.sh

  # Distributed in-memory cache
  redis:
    image: redis:3.2.9-alpine
    read_only: true
    volumes:
      - redis:/data
    user: redis

volumes:
  db:
  redis:
  yarn:
